extends RefCounted

func cards(g:Node) -> void:
	while g.page=="dialogue": g._next_card()

func settle(g:Node) -> void:
	await g.get_tree().physics_frame
	await g.get_tree().physics_frame

func run(g:Node) -> void:
	await settle(g)
	# An unfinished v1 save preserves the player's exact estate progress.
	var legacy={"version":1,"started":true,"finished":false,"position":[1.5,0,-1],"flask":2,"evidence":["wounds"]}
	assert(g.state.restore(legacy))
	assert(g.state.world=="estate" and g.state.evidence==["wounds"] and g.state.flask==2)
	legacy.finished=true
	assert(g.state.restore(legacy))
	assert(g.state.world=="town" and g.state.estate_complete and not g.state.finished)
	print("TOWN PASS: unfinished and completed v1 saves migrate without losing evidence or resources")
	# Minimal investigation: no board and no optional witness topics are required.
	g.state=g.CaseState.new()
	g.state.started=true
	g.state.discover("eight")
	g.state.complete_report("Observations filed")
	g.state.estate_complete=true
	g._travel("town",Vector3(0,0.1,17))
	await settle(g)
	await g._walk_to(Vector3(-18,0,-5.3))
	assert(g.focused=="street_precinct")
	g._interact("street_precinct")
	await settle(g)
	await g._walk_to(Vector3(0,0,-1.3))
	assert(g.focused=="intake")
	g._interact("intake")
	cards(g)
	assert(g.state.intake_done and g.state.evidence.has("intake"))
	assert(g.state.report_evidence==["eight"])
	await g._walk_to(Vector3(0,0,7.0))
	g._interact("interior_exit")
	g.yaw=0
	await settle(g)
	await g._walk_to(Vector3(-1,0,-5.3))
	assert(g.focused=="street_almy")
	g._interact("street_almy")
	await settle(g)
	await g._walk_to(Vector3(4,0,1))
	await g._walk_to(Vector3(4,0,-4.1))
	await g._walk_to(Vector3(1.7,0,-3.7))
	assert(g.focused=="almy","Mrs. Almy must be reachable around the table")
	g._interact("almy")
	cards(g)
	assert(g.page=="witness")
	# Select the real first question button, rather than directly granting a fact.
	var choices=g.content.find_children("*","Button",true,false)
	assert(choices.size()>=2)
	choices[0].pressed.emit()
	cards(g)
	assert(g.state.evidence.has("naomi"))
	assert(not g.state.evidence.has("lay_lead") and not g.state.evidence.has("lodging"))
	g._close()
	await g._walk_to(Vector3(4,0,-4.1))
	await g._walk_to(Vector3(4,0,4.5))
	await g._walk_to(Vector3(0,0,7.0))
	g._interact("interior_exit")
	g.yaw=0
	await settle(g)
	await g._walk_to(Vector3(18,0,-5.3))
	assert(g.focused=="street_room")
	g._interact("street_room")
	await settle(g)
	await g._walk_to(Vector3(3.5,0,-2.7))
	assert(g.focused=="day_close")
	g._interact("day_close")
	cards(g)
	assert(g.state.finished and g.page=="ending")
	assert(not g.state.supplement_filed)
	print("TOWN PASS: actual movement through all three buildings; minimal uniformed inquiry reaches completion without the board or optional topics")
	# Enriched run: incoming report and county original remain immutable.
	g.state=g.CaseState.new()
	g.state.started=true
	for id in ["eight","wounds","gas"]: g.state.discover(id)
	g.state.complete_report("Full inquest requested")
	g.state.estate_complete=true
	g._travel("precinct",Vector3(0,0.1,-1.3))
	await settle(g)
	g._interact("intake")
	cards(g)
	assert(g.state.county_dispatched)
	var original=g.state.report_evidence.duplicate()
	var county=g.state.county_evidence.duplicate()
	g.state.coat="Plain wool coat"
	g._travel("boardinghouse",Vector3(4,0.1,-4))
	await settle(g)
	g._interact("almy")
	cards(g)
	choices=g.content.find_children("*","Button",true,false)
	choices[0].pressed.emit()
	cards(g)
	for id in ["lay_lead","service_work","lodging"]:
		g._town_observation(id)
		cards(g)
	g._travel("precinct",Vector3(-5,0.1,2.1))
	await settle(g)
	g._file_supplement(true)
	cards(g)
	assert(g.state.report_evidence==original and g.state.county_evidence==county)
	assert(g.state.supplement_evidence.has("naomi") and g.state.supplement_evidence.has("lodging"))
	var supplement=g.state.supplement_history[0].duplicate(true)
	g.state.discover("gazette")
	g._file_supplement(false)
	cards(g)
	assert(g.state.supplement_history.size()==2)
	assert(g.state.supplement_history[0]==supplement)
	g.state.complete_report("Observations filed")
	assert(g.state.report=="Full inquest requested" and g.state.report_evidence==original)
	g._travel("room",Vector3(0,0.1,6))
	await settle(g)
	await g._walk_to(Vector3(0,0,-6.1))
	assert(g.focused=="board")
	g._interact("board")
	assert(g.page=="board")
	g._close()
	g.comfort_time=38
	assert(g._save_game())
	g.state=g.CaseState.new()
	g._load_game()
	assert(g.state.world=="room" and g.state.supplement_history.size()==2)
	assert(g.state.county_evidence==county and g.state.report_evidence==original)
	assert(g.state.coat=="Plain wool coat" and g.comfort_time==38)
	assert(g.player.position.distance_to(Vector3(0,0,-6.1))<0.6)
	print("TOWN PASS: optional inquiry, corroboration, county dispatch, immutable originals and supplement history, board, cross-location save/load")
	g.get_tree().quit()
